Automated behavioral tests can now be run either on a host on which the IDA service is installed, in which case all tests are run, or against a remote IDA service instance, in which case a subset of tests are run, limited to tests which only require user credentials. This enables testing in all environments from which users are likely to be using the command line tools.
All test data which is uploaded to the configured IDA service instance by the automated tests is put into a timestamped and token unique folder to avoid collision with existing data or other tests.

Support is provided for netrc for secure configuration of credentials. The same configuration used for the command line tools also can be utilized for executing tests using only user credentials.

diff --git a/tests/utils/initialize-venv b/tests/utils/initialize-venv
--- a/tests/utils/initialize-venv
+++ b/tests/utils/initialize-venv
@@ -1,7 +1,8 @@
-#--------------------------------------------------------------------------------
+#!/usr/bin/env bash
+# --------------------------------------------------------------------------------
 # This file is part of the IDA research data storage service
 #
-# Copyright (C) 2018 Ministry of Education and Culture, Finland
+# Copyright (C) 2022 Ministry of Education and Culture, Finland
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published
@@ -19,13 +20,30 @@
 # @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
 # @license  GNU Affero General Public License, version 3
 # @link     https://research.csc.fi/
-#--------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------
 
-This subdirectory contains behavioral tests for the IDA command line tools. It
-depends on there being an installation of the IDA service on the same localhost,
-located in /var/ida, and utilizes the IDA configuration and test utility scripts.
+SCRIPT_ROOT=`dirname "$(realpath $0)"`
+TEST_ROOT=`dirname "$SCRIPT_ROOT"`
 
-RUNNING TESTS:
+PYTHON="/opt/fairdata/python3/bin/python"
 
-The tests folder contains a script 'run-tests' which will run all tests.
+if [ ! -x "$PYTHON" ]; then
+   PYTHON=`which python3`
+fi
 
+if [ ! -x "$PYTHON" ]; then
+    echo "Could not find python3 executable" >&2
+    exit 1
+fi
+
+cd $TEST_ROOT
+
+rm -fr $TEST_ROOT/venv 2>/dev/null
+
+$PYTHON -m venv $TEST_ROOT/venv
+
+source $TEST_ROOT/venv/bin/activate
+
+pip install --upgrade pip
+pip install 'wheel>=0.34.2' --force-reinstall
+pip install -r $TEST_ROOT/requirements.txt
